import {
  StateSchema,
  StateGraph,
  START,
  END,
  type GraphNode,
} from "@langchain/langgraph";
import { geminiModel, mistralAIModel, groqModel } from "./model.ai";
import { z } from "zod";
import { createAgent, providerStrategy } from "langchain";

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof State> = async (state) => {
  const [mistralResponse, groqResponse] = await Promise.all([
    mistralAIModel.invoke([
      {
        role: "system",
        content:
          "You are a helpful assistant that provides solutions to problems.",
      },
      {
        role: "user",
        content: `Problem: ${state.problem}\nProvide a solution.`,
      },
    ]),
    groqModel.invoke([
      {
        role: "system",
        content:
          "You are a helpful assistant that provides solutions to problems.",
      },
      {
        role: "user",
        content: `Problem: ${state.problem}\nProvide a solution.`,
      },
    ]),
  ]);
  return {
    solution_1: String(mistralResponse.content),
    solution_2: String(groqResponse.content),
  };
};

const judgeNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judgeAgent = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(100),
        solution_2_score: z.number().min(0).max(100),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),
    systemPrompt:
      "You are a judge tasked with evaluating two solutions generated by different AI models. Provide a score out of 100 for each solution, along with your reasoning.",
  });

  const judgeResponse = await judgeAgent.invoke({
    messages: [
      {
        role: "user",
        content: `Problem: ${problem}\nSolution 1: ${solution_1}\nSolution 2: ${solution_2}\nJudge which solution is better and provide scores (0-100) and reasoning for each solution.`,
      },
    ],
  });

  const result = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score: result?.solution_1_score ?? 0,
      solution_2_score: result?.solution_2_score ?? 0,
      solution_1_reasoning: result?.solution_1_reasoning ?? "",
      solution_2_reasoning: result?.solution_2_reasoning ?? "",
    },
  };
};

const graph = new StateGraph(State)
  .addNode("solution", solutionNode)
  .addNode("evaluate", judgeNode) 
  .addEdge(START, "solution")
  .addEdge("solution", "evaluate")
  .addEdge("evaluate", END)
  .compile();

export default graph;